### PR TITLE
Little fixes on PivotFinderTester

### PR DESCRIPTION
**Pull request by mertcorumlu**
**Link any issues if they have led to changes in the request**  

- Imported all static assertion methodes.
- Manually checked some wrong test cases and fixed them.

**Please describe the (sub-)exercises the tests are meant for**  
* GAD 6
* PivotFinderTester

### CODE REVIEW

**Comment by CrsiX** [comment]
Thanks :)
Can you confirm that those test cases are somewhat correct now? ^^

**Comment by mertcorumlu** [comment]
> Thanks :)
> Can you confirm that those test cases are somewhat correct now? ^^

I passed all local tests with my implementation, which passes private tests on artemis. But who knows :)

**Comment by CrsiX** [comment]
Well, that may be enough :D
If someone else has 100% in Artemis but fails any of those tests, I expect them to open an issue here.

**Comment by babyygemperor** [comment]
Oh damn, I just checked it with proper logic, apparently my implementation is not 100% correct. There's a small mistake in it. But since I still have 100%, albeit with an almost correct solution.
I'll change the test in a way, that both the values are accepted as correct values. Haha! Thanks for letting me know.

**Pull request merged**
