### PR TITLE
Action checkstyle

### LINKED ISSUE #38: Add a CI pipeline to check for build errors and Java style guide violations
Considering EiST with their exercise point reductions for bad code style... I would suggest to add a CI pipeline (e.g. Travis CI) to accomplish the following goals on our test suite(s):

- Prevent Java build errors
- Point out bad practices to avoid them later on
- Improve general coding style
- Encourage other students to adapt the idea of testing their own projects in this or similar way as well

After a quick search, there are some style guides around, e.g. [this](https://google.github.io/styleguide/javaguide.html) one from Google or [this](https://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html) draft for OpenJDK (or [this](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf) very old PDF document from Oracle?). From a quick point of overview, they seem to be quiet abstract but also consistent.

But that's not of particular interest now. The questions are: Do we need it at all? What tools should be used (if we agree on that)? I'm open for further discussion. :)

### PR DESCRIPTION
**Pull request by N0W0RK**
Structure changes in .github.

Added GithubAction for CI using checkstyle with the [Artemis configuration](https://github.com/ls1intum/Artemis/tree/develop/src/main/resources/templates/java/test/staticCodeAnalysisConfig) (closes #38)

### CODE REVIEW

**Comment by JohannesStoehr** [comment]
Believe me, you want to leave out `<module name="MagicNumber"/>`.
Otherwise you will have a hard time writing the tests

**Comment by CrsiX** [comment]
Based on [GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) the issue and PR template files may not be recognized correctly. For example, valid path names for the PR template seem to be:
- `/pull_request_template.md`
- `/docs/pull_request_template.md`
- `/.github/pull_request_template.md`
- `/.github/PULL_REQUEST_TEMPLATE/*`

I think we should redo the renaming of the template files.

**Comment by CrsiX** [comment]
I will add some more changes based on [this](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) document and I would really appreciate if you comment on them later on again, too. This way, we come to a solution together :)

**Comment by CrsiX** [comment]
Looks like we will have a lot of cleaning work to do if we really want to get a 'good' code base. Reviewdog reports:

> Filtered Findings (11973)

**Comment by CrsiX** [comment]
We should also discuss about the setting of the `fail_on_error` value. Currently, it's `false` (default), meaning the tests will always pass with a ✔️ even if errors have been found. Otherwise (`true`), they would fail with a ❌ sign.
And finally, we could also add a badge to our README to show all users looking at the GitHub page that we have java style checkers in place (and they actually reported tons of style errors) ...

**Comment by JohannesStoehr** [comment]
> Looks like we will have a lot of cleaning work to do if we really want to get a 'good' code base. Reviewdog reports:
> 
> > Filtered Findings (11973)
:monkaGiga:
But a lot of errors seem to come from too long lines. Maybe running a linter once over every file would already fix a lot of these reported errors?

**Comment by N0W0RK** [comment]
First of all sory for fucking up the template location and configuration.

As far as I care, at least the line length case can be, either commented out or removed completely. We are creating sometimes large arrays with specific values as test algortithms would present a solution.

Failing on Error sounds like a good idea. Having Tests that dont compile does not sound reasonable to me.

We might also unify the names for the actions. I think there are 2/3 different names in the config.

**Comment by N0W0RK** [comment]
First of all sory for fucking up the template location and configuration aswell as the path to the config.

As far as I care, at least the line length case can be, either commented out or removed completely. We are creating some large arrays with specific values as test algortithms would present a solution.

I think not failing when the file has an error does not make too much sense.

We should also try to unify the names for the checks. I think there are 2/3 Names in the config.

**Review by CrsiX — APPROVED** [review]
I would be fine with this settings now. Fine grained tuning can be done later on, too. Any other suggestions or comments on that? @N0W0RK

**Pull request merged**
