### PR TITLE
Create GPLv3 License and open for review

### PR DESCRIPTION
**Pull request by N0W0RK**
Adding GPLv3 license to the project. This has to be accepted by all contributors first,

### CODE REVIEW

**Comment by N0W0RK** [comment]
Feedback by @Marcel510 , @andreemic , @CrsiX , @babyygemperor and @quarz12 would be appreciated :)

**Review by quarz12 — APPROVED** [review]

**Comment by CrsiX** [comment]
I approve :)

**Review by babyygemperor — APPROVED** [review]
I approve, good idea

**Comment by Marcel510** [comment]
Looks good 👍

**Review by CrsiX — APPROVED** [review]

**Comment by CrsiX** [comment]
Since nobody complained about it over the last week, I will now merge the PR to enable the GPLv3 license for this project

**Pull request merged**
