### PR TITLE
Linked tests of selection sort in SelectionsortTester.java

### PR DESCRIPTION
**Pull request by babyygemperor**
**Link any issues if they have led to changes in the request**  

**Please describe the (sub-)exercises the tests are meant for**  
* GAD 06 - Verbessertes Sortieren

### CODE REVIEW

**Comment by CrsiX** [comment]
Why did you add methods that seem to check the MergeSort and QuickSort stuff in a test class for the selection sort? Or did I get something wrong here?

**Comment by babyygemperor** [comment]
Those are a part of selection sort.
Those methods are using the optimisation of selection sort and henceforth added in the test of selection sort

**Comment by CrsiX** [comment]
I'm not sure. What discourages the integration of those optimized test cases in their own test classes (i.e. `MergesortTester.java`)?

**Comment by JohannesStoehr** [comment]
SelectionSort is already implemented in the template. One part of the exercise expects the students to use SelectionSort in the other sorting algorithms.
So putting them into SelectionsortTester would combine the tests of the different algorithms that all belong to the same part of the exercise.

**Pull request merged**
