### PR TITLE
Added DoublePivotFinderTests

### PR DESCRIPTION
**Pull request by mertcorumlu**
**Link any issues if they have led to changes in the request**  

**Please describe the (sub-)exercises the tests are meant for**  
* GAD 6
* Tests for DualPivotFinder.

I had passed all tests on artemis and created some random cases with my implementation. I hope it works also fine with you. Make sure to run them on your computer before merging into main branch.

### CODE REVIEW

**Comment by babyygemperor** [comment]
I tried running the tests on my side. I'm passing firstLastPivot() and randomPivot()
However in medianPivotFront() and in medianPivotDistributed(), although the values are same, the tests expect them to be in a different order, like for example in `assertArrayEquals(new int[]{0, 1}, DualPivotFinder.getMedianPivotDistributed(5).findPivot(arr, 0, 1));`
My code is returning `new int[] {1, 0}` which is why it's failing all of them. Would be great if you could fix it in a way, that both variants are excepted. You could do it by asserting the size of the returned array first, and then with `Arrays.asList().contains()` or `ArrayUtils.contains()`

Apart from that @ author is normally at the end of the docs, not in the beginning

And if your tests expect only the first median to be returned in the median tests, please mention that in the docs as well :D 

Otherwise it looks good, thanks for contributing

**Comment by mertcorumlu** [comment]
> However in medianPivotFront() and in medianPivotDistributed(), although the values are same, the tests expect them to be in a different order, like for example in `assertArrayEquals(new int[]{0, 1}, DualPivotFinder.getMedianPivotDistributed(5).findPivot(arr, 0, 1));`

I think the order of indexes matters as "Der zuerst zurückgegebene Index soll dabei der Index des kleineren Pivots sein.".
`
arr = new int[] {66, 212, 256, 133, 124};
assertArrayEquals(new int[]{0, 1}, DualPivotFinder.getMedianPivotDistributed(5).findPivot(arr, 0, 1));
`
For example we should return indexes 0 and 1, but to decide on order we compare 66 to 212 and return [0,1]

`
arr = new int[] {213, 180, 93, 90, 46};
        assertArrayEquals(new int[]{3, 2}, DualPivotFinder.getMedianPivotFront(5).findPivot(arr, 2, 3));
`

In that case 93 > 90, so we return [3,2] but not [2,3] as the problem statement tells us to return the index of smaller pivots first

I hope I am understanding the problem statement correct. Otherwise I should not be passing the tests on artemis.

> Apart from that @ author is normally at the end of the docs, not in the beginning

Thats the result of writing tests midnight :)

> And if your tests expect only the first median to be returned in the median tests, please mention that in the docs as well :D

Where is that the case ?

**Comment by babyygemperor** [comment]
> I think the order of indexes matters as "Der zuerst zurückgegebene Index soll dabei der Index des kleineren Pivots sein.".
Oh wait true. I forgot about that

> I hope I am understanding the problem statement correct. Otherwise I should not be passing the tests on artemis.
Haha, yes. The problem is, I have 100% on Artemis but I'm not passing your tests, so lemme dig deeper a bit as to why it is happening.

> Thats the result of writing tests midnight :)
Happens, been there

> > And if your tests expect only the first median to be returned in the median tests, please mention that in the docs as well :D
> 
> Where is that the case ?
When there are duplicates of the medians, according to Artemis, index of any of the median can be returned, but in the tests it expects a certain index. So in case your tests expects the returned index to be the index of the first median, kindly mention it in the docs. For example in the array of `[12839, -1231, 1, 69, 12, 69, 69]`, the considered elements for the median came out to be `[1, 12, 69, 69, 69,]` The median is 69, but there are 3 possible indices for it. Which one of them is your test expecting, index 3 or 5 or 6? (Complete hypothetical example)

**Comment by babyygemperor** [comment]
Alright okay, I've found the problem
>Die beiden MedianImplementierungen werden nur für den Parameter 5 getestet. Das heißt es sollen die Indices vom zweit kleinsten und zweit größten Element zurückgegeben werden.

Now because the index of the 2nd smallest element is the index of the largest element and the index of the 2nd largest element the index of the smallest element, I was getting my array the other way round.

So in general when the interval range is less than 4, I won't pass your test since it's stricter than Artemis tests, and my code "forgot" to check it, and so did Artemis.

Also please forget this
>Would be great if you could fix it in a way, that both variants are excepted.

That was just plain blind and dumb

**Comment by babyygemperor** [comment]
And many of your tests are testing exactly the part of the code I didn't implement xD so I really can't guarantee the correctness of the median tests

**Comment by mertcorumlu** [comment]
> Would be great if you could fix it in a way, that both variants are excepted.

I think you are right about that. I will update the tests in a such way that it accepts both cases, but will display a warning that it is not tested on Artemis but it is in problem statement.

> When there are duplicates of the medians, according to Artemis, index of any of the median can be returned, but in the >tests it expects a certain index. So in case your tests expects the returned index to be the index of the first median, kindly >mention it in the docs. For example in the array of [12839, -1231, 1, 69, 12, 69, 69], the considered elements for the >median came out to be [1, 12, 69, 69, 69,] The median is 69, but there are 3 possible indices for it. Which one of them is >your test expecting, index 3 or 5 or 6? (Complete hypothetical example)

You are right about that one, I can make sure that test array is distinct or check if required and provided indexes points to same pivot. Let's see.

>And many of your tests are testing exactly the part of the code I didn't implement xD so I really can't guarantee the >correctness of the median tests

If there are still cases which Artemis doesn't test but I do please let me know.

**Comment by babyygemperor** [comment]
> If there are still cases which Artemis doesn't test but I do please let me know.

I mean, I'm not really sure if Artemis doesn't test those cases at all, or accepts both of our solutions. It could be both the possibilities. Only 1 person knows the answer to this

**Review by babyygemperor — APPROVED** [review]
Alright, since you have passed all the tests in Artemis, I think it's fair to approve your pull request, albeit I'll be adding my own test (in 5-10 mins), because allegedly there are 2 possible solutions.
Thanks a lot for contributing

**Pull request merged**
