### PR TITLE
Added more tests for QuickSort and fixed an issue

### PR DESCRIPTION
**Pull request by babyygemperor**
**Link any issues if they have led to changes in the request**  
https://github.com/N0W0RK/TUM_GAD_Tests_SS21/pull/28#discussion_r639720165

**Please describe the (sub-)exercises the tests are meant for**  
* GAD 06 - Verbessertes Sortieren

Added tests for QuickSort using all the pivot options without any selection sort based optimisation

Would appreciate a review before I blindly merge it with main again

### CODE REVIEW

**Comment by CrsiX** [comment]
Oh, that's a bunch of new stuff. It's more of a feature request than a fix request :D
Give me some time for review pls :)

**Comment by CrsiX** [comment]
Based on [this source](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html), the `@version` tag for JavaDoc must not be used on methods, only interfaces and classes. I will add a commit to address this.

**Comment by CrsiX** [comment]
I need an import like `import static org.junit.jupiter.api.Assertions.*;` instead of the
`import org.junit.jupiter.api.Assertions;` in the file `QuickSortTester.java` to make it work properly. You too?

**Comment by babyygemperor** [comment]
Fixed

**Comment by CrsiX** [comment]
After some internal discussions and bug fixings, I would think this can be merged.
If someone else with 100% in Artemis fails any of our tests, I would advise them to open an issue for that.
In the future, we may use some kind of record instead of the static strings, but they seem to work for now.

**Review by CrsiX — APPROVED** [review]

**Pull request merged**
